#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Rodrigo Carvalho Silva
title: Blog do Rodrigo Carvalho Silva

# Short bio or description (displayed in the header)
description: Tecnologia, música e liberdade
tagline: Tecnologia, música e liberdade

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://s.gravatar.com/avatar/91de2067b259f05dcefa3b29ee10a5dd?s=140

#
# Flags below are optional
#

paginate:         5

cactus:
  siteName: rodsilva.com

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://rodsilva.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/
excerpt_separator: <!-- more -->

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
#sass:
#  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-webmention_io

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

webmentions:
  # Enter your webmention.io username
  username: rodsilva.com
  cache_bad_uris_for: 5
  # If you've changed domain in the past, list the old ones here
  legacy_domains:
    - https://rodrigocarvalho.blog.br
    - http://rodrigocarvalho.blog.br

# Prose.io configuration
prose:
  rooturl: '_posts'
  siteurl: 'https://rodsilva.com/'
  relativeLinks: 'https://rodsilva.com/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "hidden"
          value: "Rodrigo Carvalho"
      - name: "title"
        field:
          element: "text"
          label: "Título"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comentários"
          value: true
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categorias"
          placeholder: "Escolha as categorias"
          alterable: true
          options:
            - name: "Música"
              value: "Música"
            - name: "Tecnologia"
              value: "Tecnologia"
            - name: "Liberdade"
              value: "Liberdade"
            - name: "Dicas"
              value: "Dicas"
            - name: "Privacidade"
              value: "Privacidade"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          placeholder: "Escolha as tags"
          alterable: true
          options:
